### ISSUE TITLE
Doesn't handle last,first

### ISSUE THREAD

**Issue by Twitort** [jamescurran/HumanNameParser#1]
Does not properly parse a name formatted as "last,first" with no spaces around the comma. This results in the full name being classified as just the last name. Interestingly, if you add a middle name onto this, it does correctly parse all of the names: "last,first middle".

Simple fix for this is to change the following in the Parse method:
`if (name.IndexOf(' ') == -1)`
to
`if (name.IndexOf(' ') == -1 && name.IndexOf(',') == -1)`

**Comment by jamescurran** [comment]
Thanks for the report and fix.
